
local Assets = {
	Images = {

	},
	Animations = {
		Default = {
			Idle = "rbxassetid://14316902942",
			Walk = "rbxassetid://14316891234",
			Sprint = "rbxassetid://14316882828",
			Jump = "rbxassetid://14103333094",
			Fall = "rbxassetid://507767968",
			Climb = "rbxassetid://507765644",
			Wave = "rbxassetid://507770239",
			Point = "rbxassetid://507770453",
			Dance = "rbxassetid://507771019",
			Dance2 = "rbxassetid://507776043",
			Dance3 = "rbxassetid://507777268",
			Laugh = "rbxassetid://507770818",
			Cheer = "rbxassetid://507770677",
		},
	},
	Sounds = {
	},
	Models = {
		Circles = {
			FrontSingle = "rbxassetid://5798530278",
		},
	},
}

return Assets
